sudo: false
language: ruby
rvm:
  - 2.6.3
before_install: gem install bundler
before_script:
  - bundle install
script: bundle exec rspec
notifications:
  email:
    on_success: never
    on_failure: always
