FROM ruby:2.6.5-alpine

RUN apk add --update --no-cache tzdata openssh-client less git build-base
RUN cp /usr/share/zoneinfo/Asia/Yekaterinburg /etc/localtime && echo 'Asia/Yekaterinburg' > /etc/timezone

RUN ssh-keyscan -H github.com >> /etc/ssh/ssh_known_hosts

ENV BUNDLE_APP_CONFIG /app/.bundle

RUN echo 'gem: --no-rdoc --no-ri --no-document' > /root/.gemrc
RUN gem install 'bundler:2.0.2' rubocop

WORKDIR /app
