FROM ruby:2.6.3

RUN ln -fs /usr/share/zoneinfo/Asia/Yekaterinburg /etc/localtime \
  && dpkg-reconfigure -f noninteractive tzdata

RUN echo 'gem: --no-rdoc --no-ri --no-document' > /root/.gemrc
RUN gem install bundler

WORKDIR /app
