version: '3.3'

services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dip
      args:
        DOCKER_RUBY_VERSION: $DOCKER_RUBY_VERSION
      labels:
        com.yandex-client.ruby.version: $DOCKER_RUBY_VERSION
    environment:
      - BUNDLE_PATH=/bundle/${DOCKER_RUBY_VERSION}
    volumes:
      - ..:/app
      - bundler-data:/bundle
    command: sh

volumes:
  bundler-data:
    external:
      name: bundler_data
