version: '2'

services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.${DOCKER_RUBY_VERSION}
    environment:
      - BUNDLE_PATH=/bundle/$DOCKER_RUBY_VERSION
      - SSH_AUTH_SOCK=/ssh/auth/sock
      - TEST_DB_HOST=db
      - TEST_DB_NAME=docker
      - TEST_DB_USERNAME=postgres
    command: bash
    depends_on:
      - db

  db:
    image: postgres:$POSTGRES_IMAGE_TAG
    environment:
      - POSTGRES_DB=docker
